spring.main.web-environment: false
spring.profiles.active: prod

successful_tests_dir: successful-tests/
failed_tests_dir: failed-tests/

wait-for-test-to-finish-in-sec : 110
wait-For-Finish-identifier : 10000
sleep_interval_in_seconds: 10
client.version: 5.0.0

gateway_url : http://ec2-52-28-182-127.eu-central-1.compute.amazonaws.com:8008/
#gateway_url : http://localhost:8008/

logging:
  level:
    org.springframework.web: ERROR
    caseyellow.client: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] - %-5p %c{1}:%L - [%X{correlation-id}] - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] - %-5p %c{1}:%L - [%X{correlation-id}] - %m%n"
  file: logs/client_log